name: Template Parameter TrueDeltaPT
isEnabled: true

printDialSetsSummary: true

nominalStepSize: 0.1
useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: Template Parameter TrueDeltaPT dialSetDefinitions
    # 'applyOnDataSets' can take a list or a wildcard
    applyOnDataSets: ["*"]
    parametersBinningPath: "${GUNDAM_CONFIG_DIR}/binnings/binning_TrueDeltaPT.txt"
    applyCondition: "[IsSignal] == 1"
    printDialsSummary: true

parameterLimits:
  minValue: 0.
  maxValue: 3.0
