name: Template Parameter TrueMuonP
isEnabled: true

printDialSetsSummary: true

nominalStepSize: 0.1
useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: Template Parameter TrueMuonP dialSetDefinitions
    applyOnDataSets: ["ICARUSGUNDAMWorkshop25"]
    parametersBinningPath: "${GUNDAM_CONFIG_DIR}/binnings/binning_TrueMuonP.txt"
    applyCondition: "[IsSignal] == 1"
    printDialsSummary: true

parameterLimits:
  minValue: 0.
  maxValue: 3.0
