fitSampleList:
  - name: "TrueMuonP_XS"
    isEnabled: true
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_TrueMuonP.txt"

    selectionCuts: "" # (numu+numubar)
    #selectionCuts: "TrueE>0.3" # (numu+numubar) but Enu>0.3 GeV
    #selectionCuts: "TrueE>0.3 && TruePDG>0." # (numu) but Enu>0.3 GeV

    dataSets: ["ICARUSNuMI_1mu2p0pi_true"]
    parameterSetName: "Template Parameter TrueMuonP"
    yAxis: "#frac{d #sigma}{d p_{#mu}} #frac{cm^{2}}{Ar GeV/c}"
    normaliseParameterList:
      - name: "Constant flux"
        isEnabled: true

        meanValue: 6.2760039e+11 # (numu+numubar)/cm^2, g3chase applied, POT = 8.0746178e+20
        stdDev: 7.9037791e+10 # sqrt(9.2^2 + 8.6^2) = 12.59%

        #meanValue: 2.7161302e+11 # (numu+numubar)/cm^2, g3chase applied, POT = 8.0746178e+20, but Enu>0.3 GeV
        #stdDev: 3.1299073e+10 # sqrt(7.67^2 + 8.6^2) = 11.52%

        #meanValue: 1.7514826e+11 # (numu)/cm^2, g3chase applied, POT = 8.0746178e+20, but Enu>0.3 GeV
        #stdDev: 2.2263101e+10 # sqrt(9.36^2 + 8.6^2) = 12.71%

      - name: "Number of targets"
        ### Using MC value assumed from sbn-doc-33224, converted to N NUCLEONS instead of N Nuclei
        # USING N Ar NUCLEI
        # Let's assume a 0.2% uncertainty for now... (NOTE: **if** my math is right we may need to scale up by 0.2% in data...)
        meanValue: 4.714056E30
        stdDev: 9.4281120e+27
