# Config for gundamFitter: starting based on screenshots on sbn-doc-32028... let's see

#outputFolder: "${GUNDAM_CONFIG_DIR}/output/"
minGundamVersion: 1.9.0

xsecCalcConfig:
  enableStatThrowInToys: true
  enableEventMcThrow: true

fitterEngineConfig:

  # minimizer
  minimizerConfig: "${GUNDAM_CONFIG_DIR}/Configs_Minimizer/default_minimizer.yaml"

  # likelihoodInterface
  likelihoodInterfaceConfig:

    # jointProbability
    jointProbabilityConfig:
      type: "PoissonLLH"
      #type: "BarlowLLH"

    # dataSetManager
    propagatorConfig:
      parametersManagerConfig:
        parameterSetList: "${GUNDAM_CONFIG_DIR}/Configs_ParameterSetList/parameterSetList_MuonP.yaml"
      fitSampleSetConfig: "${GUNDAM_CONFIG_DIR}/Configs_FitSampleSet/fitSamples_TrueMuonP.yaml"

    dataSetList: "${GUNDAM_CONFIG_DIR}/Configs_DataSetList/dataSetListConfig_Example_True.yaml"
      #plotGeneratorConfig: "${GUNDAM_CONFIG_DIR}/Configs_PlotGenerator/plotConfigs_TrueMuonP.yaml"

